version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/poolgaming
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  leitor:
    image: alpine:latest
    command: ["cat", "/dados/arquivo.txt"]
    volumes:
      - ./dados:/dados

volumes:
  mongo-data: