FROM node:20

WORKDIR /app

# Copia primeiro apenas os arquivos de definição de dependências
COPY package*.json ./

# Instala dependências antes de copiar o restante (melhora cache)
RUN npm install --legacy-peer-deps

# Copia o restante dos arquivos do projeto
COPY . .

# Faz o build
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]